### ISSUE TITLE
Install failed using Homebridge Config UI

### ISSUE THREAD

**Issue by drawn2lights** [nicoduj/homebridge-deebotEcovacs#25] opened 2020-06-03 02:55 UTC
Attempted to install it with the homebridge config ui x version 4.21.0. Output below: 

npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js

> canvas@2.6.1 install /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-glibc-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.16.3 (node-v72 ABI, glibc) (falling back to source compile with node-gyp) 
Package pixman-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `pixman-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pixman-1' found
gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.97-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Linux 4.19.97-v7+
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas
node-pre-gyp ERR! node -v v12.16.3
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/usr/local/lib/node_modules/homebridge-deebotecovacs/node_modules/canvas/build/Release --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v72' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-06-03T02_48_31_095Z-debug.log

Command failed. Please review log for details.

**Comment by nicoduj** [comment] 2020-06-03 15:25
Hi, check the readme for package to install as prerequisites in order to build canvas for your platform

**Comment by markyuk** [comment] 2020-06-15 07:52
I've got the same issue here.

I've added:
**apk add build-base cairo-dev jpeg-dev pango-dev giflib-dev librsvg-dev**
to the startup script and restarted

And it starts to go downhill from here:

> USER: root
> DIR: /homebridge
> CMD: npm install --save homebridge-deebotecovacs@latest
> 
> npm WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
> npm WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
> 
> > canvas@2.6.1 install /homebridge/node_modules/homebridge-deebotecovacs/node_modules/canvas
> > node-pre-gyp install --fallback-to-build
> 
> 
> node-pre-gyp WARN Using request for node-pre-gyp https download 
> node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v72-linux-musl-x64.tar.gz 
> node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@12.16.2 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
> Package pixman-1 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `pixman-1.pc'
> to the PKG_CONFIG_PATH environment variable
>

**Comment by markyuk** [comment] 2020-06-16 15:35
Well, I've tried changing the startup script to be:

`apk add build-base libpixman-1-dev cairo-dev jpeg-dev pango-dev giflib-dev librsvg-dev`

But it's not solved the issue - still failing at the same place when enabling the plugin.

Anyone else have any ideas?

**Comment by nicoduj** [comment] 2020-06-19 11:36
Hi, what environment are you in ? did you check prerequisit eon this link : https://github.com/Automattic/node-canvas#compiling

**Comment by markyuk** [comment] 2020-06-19 14:41
Hi

I'm on Synology Diskstation NAS DS713+ - and no, not checked the compilation list as yet - I figured it would just work, sorry.  Got about 10 plugins and this is the first one to kick up a fuss :-)  I'll try and look on the weekend, thanks

**Comment by markyuk** [comment] 2020-06-26 07:05
I've got this installed on my Diskstation NAS (it shows up as a plugin in the homebridge UI)

But I'm now seeing this when it loads -

```
[6/26/2020, 7:03:01 AM] [DeebotEcovacs] Initializing DeebotEcovacs platform...
[6/26/2020, 7:03:01 AM] TypeError: Cannot read property 'continent' of undefined
    at new DeebotEcovacsAPI (/homebridge/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js:22:48)
    at new myDeebotEcovacsPlatform (/homebridge/node_modules/homebridge-deebotecovacs/index.js:25:27)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
```

So it never properly loads and I don't see my Ozmo 950 in the UI.

Any help greatly appreciated.  Like others here, we're using Homebridge UI simply as our skills don't run to complex Linux work and need handholding, sorry!

**Comment by markyuk** [comment] 2020-07-02 11:22
Sorry to bother - anyone any ideas on this?

**Comment by mrbungle64** [comment] 2020-07-04 07:35
@markyuk 

> Sorry to bother - anyone any ideas on this?

What country code are you using?
https://github.com/nicoduj/homebridge-deebotEcovacs#homebridge-configuration

It must be one of these:
https://github.com/mrbungle64/ecovacs-deebot.js/blob/master/countries.js

**Comment by markyuk** [comment] 2020-07-08 13:50
Hi there

GB is not in the list, so I've selected OTHER.

I can install correctly but on restart, I am seeing this in the logs and Homebridge isn't starting -

```
[7/8/2020, 2:49:12 PM] [DeebotEcovacs] Initializing DeebotEcovacs platform...
[7/8/2020, 2:49:12 PM] TypeError: Cannot read property 'continent' of undefined
    at new DeebotEcovacsAPI (/homebridge/node_modules/homebridge-deebotecovacs/deebotEcovacsAPI.js:22:48)
    at new myDeebotEcovacsPlatform (/homebridge/node_modules/homebridge-deebotecovacs/index.js:55:27)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:397:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:374:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:153:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

Ha, and just as I've posted, I've figured it out myself!

I went to the config file and edited and changed the country code to GB - and there are no errors in the logs.
So "OTHER" in the dropdown config setup doesn't work ... and "GB" needs adding :-)

**But I don't see any accessory for the vaccuum - what should I see?**

Just noticed the log says -

[7/10/2020, 3:28:15 PM] [DeebotEcovacs] ERROR - Failure in connecting to ecovacs to retrieve your deebots! - Error: connect ETIMEDOUT 92.242.132.24:443
[7/10/2020, 3:28:15 PM] [DeebotEcovacs] ERROR - ERROR while getting deebots, will retry discovery in 1 minute

Which appears to be an IP address with Barefuit in Belfast?

**Comment by markyuk** [comment] 2020-07-14 08:28
Does anyone else have this same issue?  Any suggestions?

**Comment by mrbungle64** [comment] 2020-07-14 20:53
@nicoduj 

I added UK as country code
https://github.com/mrbungle64/ecovacs-deebot.js/commit/15fd988300f961992325675e314f68d1057f84dc

This will be included in the next npm release of the library.

**Comment by mrbungle64** [comment] 2020-07-18 18:01
> @nicoduj
> 
> I added UK as country code
> [mrbungle64/ecovacs-deebot.js@15fd988](https://github.com/mrbungle64/ecovacs-deebot.js/commit/15fd988300f961992325675e314f68d1057f84dc)
> 
> This will be included in the next npm release of the library.

https://github.com/mrbungle64/ecovacs-deebot.js/releases/tag/0.4.17
https://www.npmjs.com/package/ecovacs-deebot/v/0.4.17

**Comment by nicoduj** [comment] 2020-07-19 17:10
Dependencies are bumped in latest release

**Comment by markyuk** [comment] 2020-07-19 17:22
Hi there

Thanks for adding the country code but this doesn’t solve my problem as I’ve described above - the plug-in installs correctly but there is no device showing and no clue how to add it.

**Comment by nicoduj** [comment] 2020-07-19 17:29
Hi,
can you share your config ? If your deebot is not discovered, you won't see anything in homekit. Launch in debug mode maybe to have more info, and try another country maybe (like FR or EU).

**Comment by mrbungle64** [comment] 2020-07-19 17:34
> Hi there
> 
> Thanks for adding the country code but this doesn’t solve my problem as I’ve described above - the plug-in installs correctly but there is no device showing and no clue how to add it.

```
TypeError: Cannot read property 'continent' of undefined
```
This error is caused by a missing country code (in this case 'UK') and it should be fixed now.

If you don't see any accessory for the vaccuum this is maybe a different issue.

**Comment by markyuk** [comment] 2020-07-20 14:16
I've installed the latest version and it's now working.  At first I tried country code EU - which obviously fails trying to get the continent from that.  I then switched to FR (as you said above) and it worked.    So I think switched to UK in config, and we're working.   Odd!

thank you!

**Comment by Jai-Gogineni** [comment] 2020-08-11 19:26
I am getting the same here is the log 

`Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to 'pkg-config cairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.4.51-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/lib/homebridge/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/var/lib/homebridge/node_modules/canvas/build/Release" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v72"
gyp ERR! cwd /var/lib/homebridge/node_modules/canvas
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error `

> But it works `v12.13.1`

**Comment by mrbungle64** [comment] 2020-08-11 19:38
> I am getting the same here is the log
> 

@Jai-Gogineni 
https://github.com/nicoduj/homebridge-deebotEcovacs#homebridge-deebotecovacs => "IMPORTANT"

**Comment by Jai-Gogineni** [comment] 2020-08-12 08:12
> > I am getting the same here is the log
> 
> @Jai-Gogineni
> https://github.com/nicoduj/homebridge-deebotEcovacs#homebridge-deebotecovacs => "IMPORTANT"

- [ ]  Awesome Thank-you, if any one still struggling add this line on the HB terminal

`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

**Comment by Jai-Gogineni** [comment] 2020-08-12 09:30
> > I am getting the same here is the log
> 
> @Jai-Gogineni
> https://github.com/nicoduj/homebridge-deebotEcovacs#homebridge-deebotecovacs => "IMPORTANT"

- [x]  Awesome Thank-you, if any one still struggling add this line on the HB terminal
`sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev`

**Comment by mrbungle64** [comment] 2020-09-15 19:45
@nicoduj 

With version 0.4.20 I removed canvas from dependencies.

https://github.com/mrbungle64/ecovacs-deebot.js/releases/tag/0.4.20
https://www.npmjs.com/package/ecovacs-deebot/v/0.4.20

**Comment by nicoduj** [comment] 2020-09-15 19:52
Great news ! Will try to update soon will be much easier

**Closed as completed** 2020-09-18 08:02 UTC
